# Generated by Django 6.0.7 on 2026-08-02 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('original_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='star',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='original_site.star'),
            preserve_default=False,
        ),
    ]
